import { AttachmentType, ServiceRequestStatus } from '@prisma/client';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { prisma } from '@/lib/prisma';
import { requireSessionUser } from '@/lib/session';
import { canApproveQuote, canManageMd, canRequestInvoice } from '@/lib/rbac';
import { approveQuoteAction, createQuoteAction, rejectQuoteAction, requestInvoiceAction, updateStatusAction, uploadAttachmentAction } from '@/lib/actions';
import { formatMoney } from '@/lib/format';

export default async function RequestPage({ params }: { params: { id: string } }) {
  const user = await requireSessionUser();
  const request = await prisma.serviceRequest.findFirst({ where: { id: params.id, ...(canManageMd(user.role) ? {} : { companyId: user.companyId ?? '' }) }, include: { company: true, requester: true, statusHistory: { include: { changedBy: true }, orderBy: { createdAt: 'desc' } }, quotes: { include: { items: true, attachment: true }, orderBy: { createdAt: 'desc' } }, attachments: { include: { uploadedBy: true }, orderBy: { createdAt: 'desc' } } } });
  if (!request) notFound();
  const latestQuote = request.quotes[0];

  return <main className="mx-auto max-w-7xl space-y-6 px-4 py-6">
    <Link href="/dashboard" className="text-sm font-semibold text-mdblue">Voltar</Link>
    <section className="card"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">{request.protocol}</h1><p className="text-sm text-slate-600">{request.company.name} - {request.tipoAparelho} {request.marca} {request.modelo}</p></div><span className="badge">{request.currentStatus}</span></div><dl className="mt-4 grid gap-3 text-sm md:grid-cols-3"><div><dt className="font-semibold">Responsavel</dt><dd>{request.responsavel}</dd></div><div><dt className="font-semibold">Telefone</dt><dd>{request.telefone}</dd></div><div><dt className="font-semibold">Serial/IMEI</dt><dd>{request.serial}</dd></div><div className="md:col-span-3"><dt className="font-semibold">Problema</dt><dd>{request.problema}</dd></div></dl></section>
    <section className="grid gap-4 lg:grid-cols-2">
      {canManageMd(user.role) ? <div className="card"><h2 className="font-semibold">Operacao MD</h2><form action={updateStatusAction} className="mt-4 grid gap-3"><input type="hidden" name="requestId" value={request.id} /><select name="status">{Object.values(ServiceRequestStatus).map((status) => <option key={status} value={status}>{status}</option>)}</select><input name="note" placeholder="Observacao do status" /><button className="btn">Alterar status</button></form><form action={createQuoteAction} className="mt-6 grid gap-3"><input type="hidden" name="requestId" value={request.id} /><input name="title" placeholder="Titulo do orcamento" required /><textarea name="description" placeholder="Descricao" /><input name="itemDescription" placeholder="Item principal" required /><input name="quantity" type="number" min="1" defaultValue="1" /><input name="unitCents" type="number" min="0" placeholder="Valor unitario em centavos" required /><input name="file" type="file" /><button className="btn">Criar/enviar orcamento</button></form></div> : null}
      <div className="card"><h2 className="font-semibold">Anexos e documentos</h2><form action={uploadAttachmentAction} className="mt-4 grid gap-3"><input type="hidden" name="requestId" value={request.id} /><select name="type"><option value={AttachmentType.FOTO_PROBLEMA}>Fotos/anexos</option><option value={AttachmentType.OS_CLIENTE}>O.S. enviada pelo cliente</option><option value={AttachmentType.OS_ASSINADA_MD}>O.S. assinada pela MD</option><option value={AttachmentType.NOTA_FISCAL}>Nota fiscal</option><option value={AttachmentType.OUTRO}>Outro</option></select><input name="file" type="file" required /><button className="btn">Enviar anexo</button></form>{canRequestInvoice(user.role) ? <form action={requestInvoiceAction} className="mt-4"><input type="hidden" name="requestId" value={request.id} /><button className="btn-secondary">Solicitar nota fiscal</button></form> : null}<ul className="mt-4 space-y-2 text-sm">{request.attachments.map((attachment) => <li key={attachment.id} className="flex justify-between gap-3 rounded-md bg-slate-50 px-3 py-2"><span>{attachment.type} - {attachment.fileName}</span><a className="font-semibold text-mdblue" href={`/api/attachments/${attachment.id}`}>Baixar</a></li>)}</ul></div>
    </section>
    {latestQuote ? <section className="card"><h2 className="font-semibold">Orcamento</h2><p className="mt-2 text-sm text-slate-600">{latestQuote.title} - {latestQuote.status} - {formatMoney(latestQuote.totalCents)}</p>{canApproveQuote(user.role) && latestQuote.status === 'ENVIADO' ? <div className="mt-4 flex gap-3"><form action={approveQuoteAction}><input type="hidden" name="quoteId" value={latestQuote.id} /><button className="btn">Aprovar</button></form><form action={rejectQuoteAction}><input type="hidden" name="quoteId" value={latestQuote.id} /><input name="note" placeholder="Motivo da recusa" /><button className="btn-secondary">Recusar</button></form></div> : null}</section> : null}
    <section className="card"><h2 className="font-semibold">Historico de status</h2><ol className="mt-4 space-y-3 text-sm">{request.statusHistory.map((item) => <li key={item.id} className="border-l-2 border-mdblue pl-3"><strong>{item.toStatus}</strong><br /><span className="text-slate-600">{item.changedBy.name} em {item.createdAt.toLocaleString('pt-BR')} {item.note ? `- ${item.note}` : ''}</span></li>)}</ol></section>
  </main>;
}
